[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/webhook/*"
  to = "https://api.perceptionist.top/webhook/:splat"
  status = 200
  force = true
